import { System } from "./server/system";
import { Block } from "./server/blocks";
import { Entity } from "./server/entities";
import { registryFood } from "./server/registry/food";
import { registryItemSkill } from "./server/registry/skill";
import { registryQuest } from "./server/registry/quest";
import { registryArticle } from "./server/registry/article";
import { registryBoss } from "./server/registry/boss";
import { registryTool } from "./server/registry/tool";
import { registryItem } from "./server/registry/item";

System.initialize();
System.eventMonitor();
System.backwardsCompatibility();
Block.eventMonitor();
Entity.eventMonitor();
Entity.spawnMonitor();
registryFood();
registryItemSkill();
registryQuest();
registryArticle();
registryBoss();
registryTool();
registryItem();