import { Block } from "./server/blocks";
import { Entity } from "./server/entities";
import { Item, Quest } from "./server/items";
import { Article } from "./server/article";
import { System } from "./server/system";
import { Music } from "./server/music";

System.initialize();
export const MOD_LOGGER = System.startLogger();
System.eventMonitor();
Block.eventMonitor();
Entity.eventsMonitor();
Entity.spawnMonitor();
Entity.skillRegister();
Item.foodMonitor();
Item.useMonitor();
Item.durabilityMonitor();
Quest.register();
Article.register();
Music.register();
