when:
  - event: push
    branch: 1.21.130+

steps:
  - name: build
    image: node
    commands:
      - npm install -g pnpm
      - pnpm approve-builds esbuild rolldown
      - pnpm install --ignore-scripts
      - pnpm run build
      - pnpm run doc
  - name: upload
    image: codeberg.org/s1m/woodpecker-upload:latest
    when:
      branch: bedrock-neo
      event: [push, pull_request, manual]
    settings:
      token:
        from_secret: artifact
      file:
        - ./dist/HiddenYears2-3.0.10.mcaddon
      package: true
  - name: deploy
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: docs
      ssh_key:
        from_secret: deploy
